version: "3"

tasks:
  fmt:
    desc: "Run clang-format"
    cmds:
      - clang-format -i src/**/*.cpp src/**/*.hpp
  qdbus-gen:
    desc: "Generate qdbus adaptors"
    dir: src/dbus
    cmds:
      - /usr/lib64/qt6/bin/qdbusxml2cpp -i ../DisplaySchemaTypes.hpp -a generated/OutputsAdaptorGen schemas/DisplaySchema.Outputs.xml
      - /usr/lib64/qt6/bin/qdbusxml2cpp -i ../DisplaySchemaTypes.hpp -a generated/ConfigAdaptorGen schemas/DisplaySchema.Config.xml
      - /usr/lib64/qt6/bin/qdbusxml2cpp -i ../DisplaySchemaTypes.hpp -a generated/OutputAdaptorGen schemas/DisplaySchema.Output.xml
      - /usr/lib64/qt6/bin/qdbusxml2cpp -i ../DisplaySchemaTypes.hpp -a generated/OutputModeAdaptorGen schemas/DisplaySchema.OutputMode.xml
  setup:
    desc: "Run cmake configuration"
    cmds:
      - cmake -DCMAKE_INSTALL_PREFIX=/usr -S . -B build -G Ninja
  build:
    desc: "Run cmake build"
    cmds:
      - cmake --build build -v
  build-watch:
    desc: "Run cmake build on file change using watchman"
    cmds:
      - watchman-make -p '**/*.cpp' '**/*.h' --run "task cook"
  cook:
    desc: "Run cmake setup and build"
    cmds:
      - task: setup
      - task: build
  install:
    desc: "Run ninja install"
    cmds:
      - sudo ninja install -C build
  fmt:
    aliases: [clang-format, format]
    desc: "Run clang-format"
    dir: src
    cmds:
      - clang-format -i main.cpp **/*.{cpp,hpp}
  wldbg-build:
    desc: "Run wldbg (wayland-debug) against build"
    env:
      QT_LOGGING_RULES: "*.debug=true"
    cmds:
      - wldbg -r ./build/bin/org.buddiesofbudgie.Services -g